name: "Report bug/issue"
description: Create a report to help us improve
labels: 'bug'
body:
- type: markdown
  attributes:
    value: |
      Please [search for existing issues](https://github.com/Xian55/WowClassicGrindBot/issues) before creating a new one.

- type: textarea
  attributes:
    label: Description
    description: What did you expect to happen and what happened instead?
  validations:
    required: true
    
- type: input
  attributes:
    label: Addon Version
    description: |
      You can see the current version upon login, if it dosen't show up, check the AddonName.toc file `## Version:` field.
    placeholder: "1.7.60"
  validations:
    required: true

- type: dropdown
  id: flavor
  attributes:
    label: World of Warcraft Client
    description: What version of World of Warcraft are are you running?
    options:
      - World of Warcraft Classic
      - The Burning Crusade Classic
      - Wrath of the Lich King Classic
      - Cataclysm Classic
      - Season of Mastery
  validations:
    required: true

- type: textarea
  attributes:
    label: Reproduction Steps
    description: Please list out the steps to reproduce your bug.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
  validations:
    required: true

- type: input
  attributes:
    label: Last Good Version
    description: |
      Was it working in a previous version? If yes, which was the last good one?
    placeholder: "1.7.60"
  validations:
    required: false

- type: textarea
  attributes:
    label: Screenshots
    description: If applicable, add screenshots to help explain your problem.
    placeholder: Click here to attach your screenshots via the editor button in the top right.
  validations:
    required: false

- type: textarea
  attributes:
    label: Logs
    description: If applicable, attach `\BlazorServer\*.log` or `\HeadlessServer\*.log` files to reduce the investigation time.
    placeholder: Please attach the **Full** log in order to avoid confusion.
  validations:
    required: false
